package com.fzj.cms.module.pojo;

import java.util.Date;

public class Title {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.articleName
     *
     * @mbggenerated
     */
    private String articlename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.articleImg
     *
     * @mbggenerated
     */
    private String articleimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.isShow
     *
     * @mbggenerated
     */
    private Boolean isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.readNum
     *
     * @mbggenerated
     */
    private Integer readnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.articleContent
     *
     * @mbggenerated
     */
    private String articlecontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.id
     *
     * @return the value of title.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.id
     *
     * @param id the value for title.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.articleName
     *
     * @return the value of title.articleName
     *
     * @mbggenerated
     */
    public String getArticlename() {
        return articlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.articleName
     *
     * @param articlename the value for title.articleName
     *
     * @mbggenerated
     */
    public void setArticlename(String articlename) {
        this.articlename = articlename == null ? null : articlename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.sort
     *
     * @return the value of title.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.sort
     *
     * @param sort the value for title.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.articleImg
     *
     * @return the value of title.articleImg
     *
     * @mbggenerated
     */
    public String getArticleimg() {
        return articleimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.articleImg
     *
     * @param articleimg the value for title.articleImg
     *
     * @mbggenerated
     */
    public void setArticleimg(String articleimg) {
        this.articleimg = articleimg == null ? null : articleimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.isShow
     *
     * @return the value of title.isShow
     *
     * @mbggenerated
     */
    public Boolean getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.isShow
     *
     * @param isshow the value for title.isShow
     *
     * @mbggenerated
     */
    public void setIsshow(Boolean isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.readNum
     *
     * @return the value of title.readNum
     *
     * @mbggenerated
     */
    public Integer getReadnum() {
        return readnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.readNum
     *
     * @param readnum the value for title.readNum
     *
     * @mbggenerated
     */
    public void setReadnum(Integer readnum) {
        this.readnum = readnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.date
     *
     * @return the value of title.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.date
     *
     * @param date the value for title.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.category
     *
     * @return the value of title.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.category
     *
     * @param category the value for title.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.articleContent
     *
     * @return the value of title.articleContent
     *
     * @mbggenerated
     */
    public String getArticlecontent() {
        return articlecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.articleContent
     *
     * @param articlecontent the value for title.articleContent
     *
     * @mbggenerated
     */
    public void setArticlecontent(String articlecontent) {
        this.articlecontent = articlecontent == null ? null : articlecontent.trim();
    }
}