package com.fzj.cms.module.mapper;

import com.fzj.cms.module.pojo.Title;
import com.fzj.cms.module.pojo.TitleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    int countByExample(TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    int deleteByExample(TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    int insert(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    int insertSelective(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    List<Title> selectByExampleWithBLOBs(TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    List<Title> selectByExample(TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    Title selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Title record, @Param("example") TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Title record, @Param("example") TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Title record, @Param("example") TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Title record);
}